## Determining the colour scheme of the faces

In [2]:
import cv2 as cv
import numpy as np

In [13]:
img = cv.imread('sample image.jpg')
cv.imshow('image', img)
cv.waitKey(0)

-1

In [4]:
img_hsv = cv.cvtColor(img, cv.COLOR_BGR2HSV)
cv.imshow('image', img)
cv.imshow('image_hsv', img_hsv)
cv.waitKey(0)

-1

In [5]:
img_hsv.shape

(608, 612, 3)

In [6]:
cv.imshow('img_hsv_partial', img_hsv[360:380,330:350])
cv.waitKey(0)

-1

In [36]:
def WHICHCOLOR(img_part):

    blue_mask = cv.inRange(img_part, np.array([90,120,120]),np.array([110,255,255]))
    result_blue = cv.bitwise_and(img_part,img_part, mask = blue_mask)
    if (result_blue != np.zeros((5,5,3)) ).all():
        print("blue")

    green_mask = cv.inRange(img_part, np.array([65,120,120]),np.array([95,255,255]))
    result_green = cv.bitwise_and(img_part,img_part, mask = green_mask)
    if (result_green != np.zeros((5,5,3)) ).all():
        print("green")
    
    white_mask = cv.inRange(img_part, np.array([0,0,0]),np.array([180,90,255]))
    result_white = cv.bitwise_and(img_part,img_part, mask = white_mask)
    if (result_white != np.zeros((5,5,3)) ).all():
        print("white")

    orange_mask = cv.inRange(img_part, np.array([9,70,70]),np.array([18,255,255]))
    result_orange = cv.bitwise_and(img_part,img_part, mask = orange_mask)
    if (result_orange != np.zeros((5,5,3)) ).all():
        print("orange")

    yellow_mask = cv.inRange(img_part, np.array([20,70,70]),np.array([65,255,255]))
    result_yellow = cv.bitwise_and(img_part,img_part, mask = yellow_mask)
    if (result_yellow != np.zeros((5,5,3)) ).all():
        print("yellow")

    red_mask = cv.inRange(img_part, np.array([0,70,120]),np.array([5,255,255]))
    result_red = cv.bitwise_and(img_part,img_part, mask = red_mask)
    if (result_red != np.zeros((5,5,3)) ).all():
        print("red")
    
    

In [38]:
#TOP FACE :
WHICHCOLOR(img_hsv[150:155,150:155])
WHICHCOLOR(img_hsv[230:235,120:125])
WHICHCOLOR(img_hsv[300:305,95 :100])
WHICHCOLOR(img_hsv[230:235,180:185])
WHICHCOLOR(img_hsv[300:305,150:155])
WHICHCOLOR(img_hsv[370:375,125:130])
WHICHCOLOR(img_hsv[299:304,209:214])
WHICHCOLOR(img_hsv[380:385,180:185])
WHICHCOLOR(img_hsv[450:455,150:155])


green
orange
green
orange
white


In [26]:
#LEFT FACE:
WHICHCOLOR(img_hsv[110:115,200:205])
WHICHCOLOR(img_hsv[175:180,230:235])
WHICHCOLOR(img_hsv[250:255,255:260])
WHICHCOLOR(img_hsv[120:125,295:300])
WHICHCOLOR(img_hsv[180:185,320:325])
WHICHCOLOR(img_hsv[250:255,365:370])
WHICHCOLOR(img_hsv[125:130,380:385])
WHICHCOLOR(img_hsv[120:125,370:375])
WHICHCOLOR(img_hsv[180:185,420:425])
WHICHCOLOR(img_hsv[250:255,445:450])

orange
yellow
red
green


## Mask Tester:

In [35]:
print(img_hsv[450:455,150:155])

h_min_val,s_min_val,v_min_val,h_max_val,s_max_val,v_max_val = 0,0,0,0,0,0

def h_max(x):
    h_max_val = x
def h_min(x):
    h_min_val = x
def s_max(x):
    s_max_val = x
def s_min(x):
    s_min_val = x
def v_max(x):
    v_max_val = x
def v_min(x):
    v_min_val = x

white_mask = cv.inRange(img_hsv, np.array([h_min_val,s_min_val,v_min_val]),np.array([h_max_val,s_max_val,v_max_val]))
result_white = cv.bitwise_and(img_hsv,img_hsv, mask = white_mask)
cv.namedWindow('img')

cv.createTrackbar('h_min','img', 0,180, h_min)
cv.createTrackbar('h_max', 'img',0,180, h_max)
cv.createTrackbar('s_min', 'img',0,255, s_min)
cv.createTrackbar('s_max', 'img',0,255, s_max)
cv.createTrackbar('v_min', 'img',0,255, v_min)
cv.createTrackbar('v_max', 'img',0,255, v_max)
cv.imshow('img',result_white)

while(1):
    cv.imshow('img',result_white)
    k = cv.waitKey(1) & 0xFF

    if k==27:
        break;

    h_min_val = cv.getTrackbarPos('h_min','img')
    h_max_val = cv.getTrackbarPos('h_max','img')
    s_min_val = cv.getTrackbarPos('s_min','img')
    s_max_val = cv.getTrackbarPos('s_max','img')
    v_min_val = cv.getTrackbarPos('v_min','img')
    v_max_val = cv.getTrackbarPos('v_max','img')
    
    
    white_mask = cv.inRange(img_hsv, np.array([h_min_val,s_min_val,v_min_val]),np.array([h_max_val,s_max_val,v_max_val]))
    result_white = cv.bitwise_and(img_hsv,img_hsv, mask = white_mask)

cv.waitKey(0)

[[[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]]


error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window_w32.cpp:2581: error: (-27:Null pointer) NULL window: 'img' in function 'cvGetTrackbarPos'


In [39]:
print(img_hsv[230:235,120:125])
cv.imshow('img',img_hsv[230:235,120:125])
cv.waitKey(0)

[[[ 12 218 251]
  [ 12 218 251]
  [ 12 218 251]
  [ 12 218 251]
  [ 12 218 251]]

 [[ 12 218 251]
  [ 12 218 251]
  [ 12 218 251]
  [ 12 218 251]
  [ 12 218 251]]

 [[ 11 217 255]
  [ 11 217 255]
  [ 11 217 255]
  [ 11 217 255]
  [ 11 217 255]]

 [[ 11 217 255]
  [ 11 217 255]
  [ 11 217 255]
  [ 11 217 255]
  [ 11 217 255]]

 [[ 11 217 255]
  [ 11 217 255]
  [ 11 217 255]
  [ 11 217 255]
  [ 11 217 255]]]


-1